server:
  port: 9090
spring:
  application:
    name: gateway


eureka:
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
zuul:
  routes:
    instance-server:
        path: /api-a/**
        url: http://localhost:8765/
    feign-client:
        path: /feign/**
        serviceId: feign-client




