server:
  port: 9090

eureka:
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      #------------------------------------------------------------------------
      - id: i5xforyou-biz-auth
        uri: http://www.baidu.com/**
        predicates:
        - Path= /hello/**
        filters:
        - StripPrefix= 1

