server:
  port: 8080
spring:
  application:
    name: ribbon-service

eureka:
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

instance-server:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8765,localhost:8766
    ServerListRefreshInterval: 15000

