server:
  port: 8770

spring:
  application:
    name: feign-client


eureka:
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/



# 开启hystrix
feign:
  hystrix:
    enabled: true
